# Generated by Django 4.2 on 2023-05-08 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='matches',
        ),
        migrations.DeleteModel(
            name='TournamentMatchRelation',
        ),
    ]
