# Generated by Django 4.2 on 2023-05-09 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_tournament_tournament_ladder'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentteam',
            name='group',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
