# Generated by Django 4.2 on 2023-05-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_tournamentteam_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
