# Generated by Django 4.2 on 2023-05-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_tournamentmatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='tournament_ladder',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('group', 'Group'), ('ladder', 'Ladder')], default='pending', max_length=10),
        ),
    ]
