# Generated by Django 4.2 on 2023-05-16 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0008_remove_tournament_tournament_ladder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_type',
            field=models.CharField(choices=[('1gr', '1 Group'), ('2gr+ldr', '2 Groups + Ladder'), ('3gr+ldr', '3 Groups + Ladder'), ('4gr+ldr', '4 Groups + Ladder'), ('ldr', 'Ladder')], default='1gr', max_length=100),
        ),
    ]
