# Generated by Django 4.2 on 2023-05-29 21:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_alter_match_match_name_alter_match_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentteam',
            old_name='group',
            new_name='group_choice',
        ),
        migrations.AddField(
            model_name='tournamentteam',
            name='final_position',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='tournamentteam',
            name='ladder_choice',
            field=models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(256)]),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('pending_group', 'Group Pending'), ('group', 'Group'), ('pending_ladder', 'Ladder Pending'), ('ladder', 'Ladder')], default='pending', max_length=20),
        ),
    ]
