# Generated by Django 4.2 on 2023-05-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_rename_group_tournamentteam_group_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('pending_group', 'Group Pending'), ('group', 'Group'), ('finished_group', 'Group Finished'), ('pending_ladder', 'Ladder Pending'), ('ladder', 'Ladder')], default='pending', max_length=20),
        ),
    ]
