# Generated by Django 4.2 on 2023-05-30 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0012_alter_tournament_tournament_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='matches_left',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
