# Generated by Django 4.2 on 2023-05-30 23:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0013_tournament_matches_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentteam',
            name='points_balance',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-150), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_group', 'Group Pending'), ('group', 'Group'), ('finished_group', 'Group Finished'), ('pending_ladder', 'Ladder Pending'), ('ladder', 'Ladder'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournamentteam',
            name='final_position',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='tournamentteam',
            name='points_lost',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='tournamentteam',
            name='points_scored',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)]),
        ),
    ]
