# Generated by Django 4.2 on 2023-05-31 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0014_tournamentteam_points_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentteam',
            name='ladder_choice',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(256)]),
        ),
    ]
