# Generated by Django 4.2 on 2023-05-31 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0018_alter_tournamentteam_final_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentteam',
            name='ladder_choice',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(256)]),
        ),
    ]
